title: Peerless Residences
email: ""
phone: ""
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://39peerless.com.au" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: 

# Permalinks
permalink: pretty
permalink: /articles/:title/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true  

collections:
  - north
  - south
  - northeast
  - southeast
  - northwest
  - southwest

# Navigation data
navigation: /data/sections.yml # Path to your navigation data file

# Include _data directory
include:
  - _data

include:
  - _pages
  - _redirects
  
# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - assets/scss
  - vendor